/**
 * @file modbus_conf.h
 * @brief Modbus defines and typedefs declarations for the componentStorage
 * ECS_Master project.
 *
 * This software is provided AS-IS.
 */

#ifndef MODBUS_CONF_H
#define MODBUS_CONF_H

#define MODBUS_SLAVE_BROADCAST 0x0000
#define MODBUS_MAX_SLAVES			 4
#define MODBUS_RX_TIMEOUT_MS	 100

#define MODBUS_LEDMODE_OFF	 0x0000
#define MODBUS_LEDMODE_ON		 0x0001
#define MODBUS_LEDMODE_VEGAS 0x0002
#define MODBUS_LEDMODE_KR		 0x0004

// Holding Registers
#define MODBUS_MODULE_SLOT_STATUS_ADDRESS 0x0000
#define MODBUS_MODULE_LEDMODE_ADDRESS			0x0029

// Input Registers
#define MODBUS_TOTAL_SLOTS_OFFSET			0x0000
#define MODBUS_FREE_SLOTS_OFFSET			0x0001
#define MODBUS_STATUS_REGISTER_OFFSET 0x0001

#define MODBUS_SR_SYSTEM_ENABLED_OFFSET 0x0000
#define MODBUS_SR_SYSTEM_ENABLED_MASK		0x0001

#define MODBUS_SR_QUEUE_EMPTY_OFFSET 0x0001
#define MODBUS_SR_QUEUE_EMPTY_MASK	 0x0001
#define MODBUS_SR_QUEUE_FULL_OFFSET	 0x0002
#define MODBUS_SR_QUEUE_FULL_MASK		 0x0001

#define MODBUS_SR_SYSTEM_READY_OFFSET 0x0003
#define MODBUS_SR_SYSTEM_READY_MASK		0x0001
#define MODBUS_SR_SYSTEM_BUSY_OFFSET	0x0004
#define MODBUS_SR_SYSTEM_BUSY_MASK		0x0001

#define MODBUS_SR_CMD_ERROR_OFFSET 0x0005
#define MODBUS_SR_CMD_ERROR_MASK	 0x0001
#define MODBUS_SR_CRC_ERROR_OFFSET 0x0006
#define MODBUS_SR_CRC_ERROR_MASK	 0x0001

#define MODBUS_ERROR_RESPONSE_MASK 0x80

typedef enum Commands {
	MODBUS_INIT,
	MODBUS_GET_STATUS,
	MODBUS_RESET_SLAVE,
} Commands_t;

typedef enum LEDMode {
	LEDMODE_OFF,
	LEDMODE_ON,
	LEDMODE_VEGAS,
	LEDMODE_KR,
} LEDMode_t;

typedef enum {
	MODBUS_OK = 0,
	MODBUS_ERROR_INIT,
	MODBUS_ERR_INVALID_ADDRESS,
	MODBUS_ERR_INVALID_FUNCTION,
	MODBUS_ERR_CRC_MISMATCH,
	MODBUS_ERR_TIMEOUT,
} ModbusError_t;

typedef enum {
	MODBUS_FUNC_READ_COILS = 0x01,
	MODBUS_FUNC_READ_DISCRETE_INPUTS,
	MODBUS_FUNC_READ_HOLDING_REGISTERS,
	MODBUS_FUNC_READ_INPUT_REGISTERS,
	MODBUS_FUNC_WRITE_SINGLE_COIL,
	MODBUS_FUNC_WRITE_SINGLE_REGISTER,
	MODBUS_FUNC_WRITE_MULTIPLE_COILS = 0x0F,
	MODBUS_FUNC_WRITE_MULTIPLE_REGISTERS,
} ModbusFunctionCode_t;

typedef struct ModbusSlave {
	uint8_t address;
	uint8_t Coils[5];
	uint16_t InputRegisters[3];
	uint16_t HoldingRegisters[42];
} ModbusSlave_t;

#endif // MODBUS_CONF_H